
version: '3'
services:

  cache_ctr:
    image: memcached
    hostname: cache_ctr
    expose:
     - "11211"
    ports:
     - "${CACHE_BIND_ADDR?cache.bind_addr must be set by the calling environment}:11211"
    restart: always
    cpuset: "21,23,25,27,29,31,33,35"

  monolith_ctr:
    build:
      context: monolith_ctr
      dockerfile: ./Dockerfile
    hostname: monolith_ctr
    expose:
     - "12345"
     - "12346"
    ports:
     - "${COMPRESS_SERVICE_GRPC_BIND_ADDR?compress_service.grpc.bind_addr must be set by the calling environment}:12345"
     - "${FRONTEND_GRPC_BIND_ADDR?frontend.grpc.bind_addr must be set by the calling environment}:12346"
    environment:
     - CACHE_DIAL_ADDR=cache_ctr:11211
     - COMPRESS_SERVICE_GRPC_BIND_ADDR=0.0.0.0:12345
     - COMPRESS_SERVICE_GRPC_DIAL_ADDR=monolith_ctr:12345
     - FRONTEND_GRPC_BIND_ADDR=0.0.0.0:12346
    restart: always
    cpuset: "5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35"

  scheduler_ctr:
    build:
      context: scheduler_ctr
      dockerfile: ./Dockerfile
    hostname: scheduler_ctr
    environment:
     - COMPRESS_SERVICE_GRPC_DIAL_ADDR=monolith_ctr:12345
    restart: always
    cpuset: "37"
